name: 构建react项目
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MESSAGE: ${{github.event.head_commit.message }}
    name: ${{ github.event.head_commit.message }} 工作
    steps:
      - name: 检查条件
        id: check
        run: |
          case "${{ env.MESSAGE }}" in
            "01"|"02"|"03"|"04"|"05"|"06"|"07"|"08"|"09"|"10")
            echo "MESSAGE 是 ${{ env.MESSAGE }} ，继续工作流"
            echo "result=true" >> $GITHUB_ENV
            ;;
            *)
            echo "MESSAGE 不满足条件，结束工作流"
            echo "result=false" >> $GITHUB_ENV
            ;;
          esac
      - name: 读取仓库内容
        if : env.result == 'true'
        uses: actions/checkout@v4

      - name: 打包项目
        if : env.result == 'true'
        uses: ./.github/actions/build-action


